# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: paul-root-permit.paul-x-change

  version: '1.0.0'
  description: The paul-root-permit credential issued by PaulXchange
  path: /paul-x-change/paul-root-permit

  topic: corp_num

  attributes:
    - legal_name
    - permit_id
    - permit_type
    - permit_issued_date
    - permit_status
    - effective_date

### eof ###

